/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./assets/js/**/*.js",
    "./public/src/components/stitch/**/*.html",
    "./public/src/components/stitch/**/*.js",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#412d00",
        "on-tertiary-fixed": "#261900",
        "tertiary-fixed": "#ffdea5",
        surface: "#111415",
        secondary: "#bdc7d9",
        "on-error-container": "#ffdad6",
        "tertiary-container": "#392700",
        "on-secondary-fixed-variant": "#3e4756",
        "secondary-fixed": "#d9e3f5",
        "on-secondary": "#27313f",
        "tertiary-fixed-dim": "#e9c176",
        "on-tertiary-fixed-variant": "#5d4201",
        "surface-container-highest": "#323536",
        outline: "#8e9098",
        "on-primary-fixed": "#091c34",
        "outline-variant": "#44474d",
        "primary-container": "#1a2b44",
        "on-primary-container": "#8292b0",
        "secondary-fixed-dim": "#bdc7d9",
        "inverse-surface": "#e1e3e4",
        "on-tertiary-container": "#af8c47",
        "surface-container-lowest": "#0c0f10",
        "on-secondary-container": "#acb6c7",
        "on-secondary-fixed": "#121c29",
        "surface-bright": "#373a3b",
        "surface-variant": "#323536",
        "on-primary-fixed-variant": "#374762",
        "inverse-primary": "#4f5f7b",
        "surface-container-high": "#282a2b",
        tertiary: "#e9c176",
        "error-container": "#93000a",
        "on-surface": "#e1e3e4",
        "primary-fixed-dim": "#b6c7e7",
        primary: "#b6c7e7",
        "on-surface-variant": "#c5c6ce",
        "secondary-container": "#3e4756",
        error: "#ffb4ab",
        "surface-dim": "#111415",
        "surface-container": "#1d2021",
        "inverse-on-surface": "#2e3132",
        "surface-tint": "#b6c7e7",
        "on-primary": "#20314a",
        "surface-container-low": "#191c1d",
        "on-error": "#690005",
        "primary-fixed": "#d5e3ff",
        background: "#111415",
        "on-background": "#e1e3e4"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        gutter: "16px",
        "data-tight": "4px",
        base: "8px",
        "section-gap": "64px",
        "container-padding": "32px",
        margin: "24px",
        xs: "4px",
        xl: "48px",
        lg: "24px",
        sm: "8px",
        md: "16px"
      },
      fontFamily: {
        h1: ["Inter"],
        "body-md": ["Inter"],
        h3: ["Inter"],
        caption: ["Inter"],
        h2: ["Inter"],
        "body-lg": ["Inter"],
        "data-label": ["Work Sans"],
        headline: ["Inter"],
        display: ["Inter"],
        body: ["Inter"],
        label: ["Work Sans"],
        "headline-md": ["Inter"],
        "headline-lg": ["Inter"],
        "label-md": ["Work Sans"]
      },
      fontSize: {
        h1: ["40px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        h3: ["24px", { lineHeight: "1.4", letterSpacing: "0", fontWeight: "600" }],
        caption: ["12px", { lineHeight: "1.4", fontWeight: "500" }],
        h2: ["32px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "data-label": ["14px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "1.4", letterSpacing: "0.02em", fontWeight: "500" }]
      }
    },
  },
  plugins: [],
}
